on:
  workflow_dispatch:
name: Azure ARM
    
env:
  targetEnv: jsdevopstest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.SERVICE_PRINCIPLE }}

      # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: wth-team14-rg
          template: ./ARM-Templates/container-webapp-template.json
          parameters: webAppName=${{env.targetEnv}}

      # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
