on:
  workflow_dispatch:
    name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main

      # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.USER_PRINCIPLE }}

      # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SERVICE_PRINCIPLE }}
          resourceGroupName: ${{ secrets.wth-team14-rg }}
          template: ./azuredeploy.json
          parameters: storageAccountType=Standard_LRS

      # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}
