# This is a basic workflow that is manually triggered

name: Triggered by issue # Name of this workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Echo Hello World
      run: echo "Issue created!!!!!!!!"
  